### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by ghost** [StephenBarnes/Canals-V2#1]
Impossible to create a world.

Forge 3.2.8
Canals 2.2

https://hastebin.com/hufeneloye.properties

**Comment by agentwolf88** [comment]
Same problem

**Comment by StephenBarnes** [comment]
Probably because some other mod is trying to generate structures that have flowing water. Any idea what mod that is? I think I've fixed it but need to test.

**Comment by ghost** [comment]
I am working on a modpack with 313 complicated mods.

I tried 2/3 mods quickly and with "The Twilight Forest" I get the problem.

**Comment by StephenBarnes** [comment]
Ok, I've made version 2.3 which should fix it. Seems to be compatible with Twilight Forest now, though for some reason the portal can't be activated sometimes. It now requires Statement Library https://www.curseforge.com/minecraft/mc-mods/statement

**Comment by TelepathicGrunt** [comment]
> Probably because some other mod is trying to generate structures that have flowing water. Any idea what mod that is? I think I've fixed it but need to test.

Yeah to help elaborate on why, Minecraft’s worldgen system is a bit fragile where it requires every single property of a block to be specified in that processor json file. So when a mod adds properties the wrong way, it blows up my mod and other worldgen datapacks as well. It has happened a few times before. But yes, switching to using Statement Library is the solution as that library found a way to add the properties to blocks without breaking the worldgen json file parsing (specifically, the BlockState codec). 

This user can confirm that updating to Canals v2.3 solve this crash with Repurposed Structures on.
https://github.com/TelepathicGrunt/RepurposedStructures/issues/150

**Comment by ghost** [comment]
Awesome everything looks like it works perfectly :), Thanks <3.

I'm closing the problem now :).
